# Generated by Django 3.0.1 on 2020-03-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='subject',
            new_name='forum',
        ),
    ]
