# Generated by Django 3.0.8 on 2020-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200711_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_text',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
