# Generated by Django 3.0.2 on 2020-03-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200222_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
