# Generated by Django 3.0.2 on 2020-03-23 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20200322_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 11, 14, 55, 80269)),
        ),
    ]
