# Generated by Django 3.0.2 on 2020-03-23 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_auto_20200323_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 22, 40, 15, 682832)),
        ),
    ]
