# Generated by Django 3.0.8 on 2020-07-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_auto_20200323_1248'),
        ('blogs', '0040_auto_20200323_2258'),
    ]

    operations = [
    ]
