# Generated by Django 3.0.8 on 2020-07-11 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_merge_20200711_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 11, 16, 40, 18, 894801)),
        ),
    ]
