# Generated by Django 3.0.8 on 2020-07-11 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0044_auto_20200711_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 11, 17, 53, 28, 287213)),
        ),
    ]
