# Generated by Django 3.0.8 on 2020-07-12 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0045_auto_20200711_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 12, 17, 16, 2, 752520)),
        ),
    ]
