# Generated by Django 3.0.2 on 2020-07-15 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_auto_20200715_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 15, 16, 51, 10, 859492)),
        ),
    ]
