# Generated by Django 3.0.8 on 2020-07-15 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0054_auto_20200715_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 15, 14, 2, 5, 291378)),
        ),
    ]
