# Generated by Django 3.0.8 on 2020-07-16 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0056_auto_20200715_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 8, 52, 4, 157647)),
        ),
    ]
