# Generated by Django 3.0.2 on 2020-07-18 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0066_auto_20200717_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 18, 14, 5, 37, 769667)),
        ),
    ]
