# Generated by Django 3.0.2 on 2020-07-18 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0067_auto_20200718_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 18, 14, 19, 41, 491627)),
        ),
    ]
