# Generated by Django 3.0.2 on 2020-07-18 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0068_auto_20200718_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 18, 22, 24, 26, 906836)),
        ),
    ]
