# Generated by Django 3.0.2 on 2020-07-18 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0069_auto_20200718_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 19, 0, 4, 36, 827762)),
        ),
    ]
