# Generated by Django 3.0.2 on 2020-07-20 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0070_auto_20200719_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 20, 15, 14, 40, 347990)),
        ),
    ]
