# Generated by Django 3.0.2 on 2020-07-20 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0071_auto_20200720_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 20, 15, 57, 21, 363568)),
        ),
    ]
