# Generated by Django 3.0.8 on 2020-07-21 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0073_auto_20200721_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 21, 12, 49, 38, 999796)),
        ),
    ]
