# Generated by Django 3.0.8 on 2020-07-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finances',
            name='transactions',
        ),
        migrations.AlterField(
            model_name='finances',
            name='Budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finances',
            name='Expenditure',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='Surplus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finances',
            name='income',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
