# Generated by Django 3.0.8 on 2020-07-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_details',
        ),
    ]
