# Generated by Django 3.0.8 on 2020-07-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_appoint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint_date',
            name='slot',
            field=models.DateField(),
        ),
    ]
