# Generated by Django 3.0.8 on 2020-07-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20200716_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint_date',
            name='slot',
            field=models.DateTimeField(),
        ),
    ]
