# Generated by Django 3.0.8 on 2020-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20200716_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint_date',
            name='slot',
            field=models.DateField(),
        ),
    ]
