# Generated by Django 3.0.8 on 2020-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20200716_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint_date',
            name='slot',
            field=models.DateTimeField(),
        ),
    ]
