# Generated by Django 3.0.8 on 2020-07-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_appoint_date_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finances',
            name='Surplus',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='transactions',
        ),
    ]
